language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/golang/lint/golint
  - dep ensure -v

script:
  - go test -cover -race -v ./...
  - go vet ./...
  - test -z "$(gofmt -d -s . | tee /dev/stderr)"
  - test -z "$(golint ./... | tee /dev/stderr)"
  - $HOME/gopath/bin/goveralls  -coverprofile=coverage.out -service=travis-ci