language: go

go:
  - 1.9

before_install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v

script:
  - go test -cover -race -v ./...
  - test -z "$(go vet ./... | tee /dev/stderr)"
  - test -z "$(gofmt -d -s . | tee /dev/stderr)"
  - golint -set_exit_status cmd/... pkg/...

notifications:
  email: false
