openapi: 3.0.1
info:
  title: Prepaid Card API
  description: |
    This is a development exercise for building a prepaid card service written in Go.

    The service has RESTful API and does not use any authentication mechanism. It is a fictional and the model is
    intentionally simplified.

    The service combines functionality to meet requirements of three actors:
    - **bank**: this is the entity controlling the service and only authorised personell must have access to these endpoints;
    - **user**: this is the cardholder;
    - **merchant**: this is a merchant, which accepts card payments via the service.
  version: 1.0.0
servers:
  -
    url: "{protocol}://{host}:{port}/api"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: "8080"
components:
  responses:
    404:
      title: Resource Not Found
      description: The requested resource cannot be found.
      $ref: "#/components/responses/404"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/error404"
  schemas:
    card:
      title: Card
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        availableBalance:
          type: string
          format: uint64
        blockedBalance:
          type: string
          format: uint64
      example:
        uuid: 68022AD3-7A94-452E-AC9C-A64F14EE5CD1
        availableBalance: "0"
        blockedBalance: "0"
    error:
      title: Error
      $ref: "#/components/schemas/error"
      type: object
      description: Problem Details Object. See [RFC7807](https://tools.ietf.org/html/rfc7807#section-3.1).
      properties:
        type:
          type: string
          required: false
          default: about:blank
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          required: false
        instance:
          type: string
          required: false
      example:
        type: /doc/error/validation
        title: Validation Error
        status: 422
        invalidParameters:
          - name: amount
            reason: must be unsigned integer
    error404:
      title: Error Not Found
      $ref: "#/components/schemas/error404"
      type: object
      description: Problem Details Object. See [RFC7807](https://tools.ietf.org/html/rfc7807#section-4.2).
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          required: false
        instance:
          type: string
          required: false
      example:
        type: about:blank
        title: Not Found
        status: 404
        instance: /card/87656343-74BF-443D-B5F8-C683FD31CFE0
paths:
  /card:
    post:
      summary: Registers a new card
      description: |
        Registers a new card.

        **Actor:** bank
      responses:
        201:
          description: A card is successfully registered and the card details are returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/card"
  /card/{uuid}:
    get:
      summary: Returns card details
      description: |
        Returns the details of card with UUID `{uuid}`.

        **Actors**: bank, user
      parameters:
        - name: uuid
          in: path
          description: The card UUID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: The card with the requested UUID is found and it's details returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/card"
        404:
          $ref: "#/components/responses/404"