openapi: 3.0.1
info:
  title: Prepaid Card API
  description: |
    This is a development exercise for building a prepaid card service written in Go.

    The service has RESTful API and does not use any authentication mechanism. It is a fictional and the model is
    intentionally simplified.

    The service combines functionality to meet requirements of three actors:
    - **bank**: this is the entity controlling the service and only authorised personell must have access to these endpoints;
    - **user**: this is the cardholder;
    - **merchant**: this is a merchant, which accepts card payments via the service.
  version: 1.0.0
servers:
  -
    url: "{protocol}://{host}:{port}/api"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: "8080"
components:
  schemas:
    card:
      title: Card
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        availableBalance:
          type: string
          format: uint64
        blockedBalance:
          type: string
          format: uint64
      example:
        uuid: 68022AD3-7A94-452E-AC9C-A64F14EE5CD1
        availableBalance: "0"
        blockedBalance: "0"
paths:
  /card:
    post:
      summary: Registers a new card
      description: |
        Registers a new card.

        **Actor:** bank
      responses:
        201:
          description: A card is successfully registered and the card details are returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/card"
